[package]
name = "pumpkin-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
bevy_xpbd_2d = "0.2.0"
fastrand = { version = "2.0.1", features = ["js"] }

